### ISSUE TITLE
Jfrog artifactory

### ISSUE THREAD

**Issue by Xharos** [islands-wars/islands#2]
### Description

Add JFrog artifactory publication

### Versions

0.2

**Comment by Vinetos** [comment]
We are waiting for this issue where any custom repository is shown
https://www.jfrog.com/jira/projects/RTFACT/issues/RTFACT-24812?filter=allopenissues
😢

**Comment by Xharos** [comment]
Current code build and deploy both core and api to our jfrog :
- http://www.jfrog.islandswars.fr:8082

We now need to add sources file and javadoc but this is not so trivial
